# Generated by Django 4.0.3 on 2022-03-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_client_cart_alter_client_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.URLField(null=True),
        ),
    ]
