# Generated by Django 4.0.1 on 2022-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='johndoe@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='movies.Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='movies',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
